---
title: "transcriptome"
author: "Lela Makharadze"
date: "26 6 2020"
output: html_document
---


```{r setup, include=FALSE, cache=FALSE}
library(TCGAbiolinks)
library(SummarizedExperiment)
library(ggplot2)
library(knitr)


knitr::opts_chunk$set(echo=T,
                      eval=T, 
                      message = F,
                      warning=F, 
                      error = F,
                      cache = F, 
                      tidy = T, 
                      size="footnotesize",
                      fig.pos='H',
                      results='hide',
                      fig.lp='fig:',
                      fig.align = 'center',
                      fig.path='figures/example-', 
                      cache.path = 'cache/example-',
                      tidy.opts=list(width.cutoff=60)
                     )
```

Data access

```{r}
listSamples <- c("TCGA-E9-A1NG-11A-52R-A14M-07","TCGA-BH-A1FC-11A-32R-A13Q-07",
                 "TCGA-A7-A13G-11A-51R-A13Q-07","TCGA-BH-A0DK-11A-13R-A089-07",
                 "TCGA-E9-A1RH-11A-34R-A169-07","TCGA-BH-A0AU-01A-11R-A12P-07",
                 "TCGA-C8-A1HJ-01A-11R-A13Q-07","TCGA-A7-A13D-01A-13R-A12P-07",
                 "TCGA-A2-A0CV-01A-31R-A115-07","TCGA-AQ-A0Y5-01A-11R-A14M-07")


query <- GDCquery(project = "TCGA-BRCA", 
                  data.category = "Gene expression",
                  data.type = "Gene expression quantification",
                  experimental.strategy = "RNA-Seq",
                  platform = "Illumina HiSeq",
                  file.type = "results",
                  barcode = listSamples, 
                  legacy = TRUE)

GDCdownload(query)

BRCARnaseqSE <- GDCprepare(query)

BRCAMatrix <- assay(BRCARnaseqSE) 
head(BRCAMatrix)


```


PCA attempt
```{r }

#data transposition 

pct <- (t(BRCAMatrix))
pc <- prcomp(pct, scale=T)
pc.sum <- summary(pc)$importance
pc.sum



```

